name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    secrets: inhetit
